name: Build and Push docker image to AWS ECR
on:
  push:
    # branches: [main]
    branches:    
      - '**'        # matches every branch
      - '!master'   # excludes master

  jobs:
    build-and-push-image
      name: Build and Push to ECR
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repository
          uses: actions/checkout@v4
        

        - name: Configuration AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
        
        - name: Build, Tag and Push the Image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_DESCRIPTION: user-management-service
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_DESCRIPTION:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_DESCRIPTION:$IMAGE_TAG