name: Build and Push docker image to AWS ECR

on:
    push:
        branches: [main]
        # branches:
        #     - '**' # matches every branch
        #     - '!master' # excludes master

env:
    ECR_REPOSITORY: user-management-service
    VERSION: patch

jobs:
    build-and-push-image:
        name: Build and Push to ECR
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Configuration AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Automatic Tagging of Releases
              id: increment-git-tag
              run: |
                  bash ./deploy/tagging.sh -v $VERSION

            - name: Build, Tag and Push the Image to Amazon ECR
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
