name: Sync labels
on:
    push:
        branches: [main]
        paths:
            - .github/workflows/sync-labels.yml
    # workflow_dispatch:

jobs:
    sync:
        name: Run EndBug/label-sync
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: EndBug/label-sync@v2
              with:
                  config-file: .github/labels.yml
