name: Code Coverage

on: [push, pull_request]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checking the Repository
              uses: actions/checkout@v4
            - name: Setting Up Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Installing Dependencies
              run: yarn install
            - name: Running Tests
              run: yarn test
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
