name: Code Coverage

on: [push, pull_request]

env:
    NODE_ENV: test
    SERVER_TEST_HOSTNAME: localhost
    SERVER_TEST_PORT: 3301

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checking the Repository
              uses: actions/checkout@v4
            - name: Setting Up Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Installing Dependencies
              run: yarn install
            - name: Create temporary .env file
              run: |
                  touch .env
                  echo NODE_ENV=$ENGINE_API_KEY >> .env
                  echo SERVER_TEST_HOSTNAME=$SERVER_TEST_HOSTNAME >> .env
                  echo SERVER_TEST_PORT=$SERVER_TEST_PORT >> .env
                  echo .env file is like:
                  cat .env
            - name: Running Tests
              run: yarn test
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
